content http://localhost:5000/api/auth/register
###

POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "aokoh",
    "password": "123456",
    "email": "aokoh@gmail.com"
}
###

POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "aokoh",
    "password": "123456"
}
###


PUT http://localhost:5000/api/users/63506fb2a8ee952f7b2026ad HTTP/1.1
content-type: application/json
Authorization: token Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzM1NTczMmQ3MzI2MzhmNmY2ZDUwOSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY2NjIyMjA0MywiZXhwIjoxNjY2NDgxMjQzfQ.gXLDOxIWEfG66hGYBc3ftsd7tdy8uuLeNOPHyxfhavw

{
    "username": "abelokoh"
}

